# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NetworkScan.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import FTPServer,HTTPServer,IPScanner,PortScanner,TelnetServer,MACScanner
import threading,re,subprocess,socket

global current, list

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.verticalLayout_4.addWidget(self.titulo)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_escaneo = QtWidgets.QWidget()
        self.tab_escaneo.setObjectName("tab_escaneo")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_escaneo)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_escaneo_actual = QtWidgets.QLabel(self.tab_escaneo)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_escaneo_actual.setFont(font)
        self.label_escaneo_actual.setObjectName("label_escaneo_actual")
        self.horizontalLayout_18.addWidget(self.label_escaneo_actual)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.verticalLayout_19.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_tipo_analisis = QtWidgets.QLabel(self.tab_escaneo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_tipo_analisis.setFont(font)
        self.label_tipo_analisis.setObjectName("label_tipo_analisis")
        self.horizontalLayout_15.addWidget(self.label_tipo_analisis)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.descripcion_rapido = QtWidgets.QLabel(self.tab_escaneo)
        self.descripcion_rapido.setObjectName("descripcion_rapido")
        self.verticalLayout_11.addWidget(self.descripcion_rapido)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.boton_an_rapido = QtWidgets.QPushButton(self.tab_escaneo)
        self.boton_an_rapido.setObjectName("boton_an_rapido")
        self.boton_an_rapido.clicked.connect(self.inicia_escaneo_rapido)
        self.horizontalLayout_14.addWidget(self.boton_an_rapido)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.descripcion_normal = QtWidgets.QLabel(self.tab_escaneo)
        self.descripcion_normal.setObjectName("descripcion_normal")
        self.verticalLayout_10.addWidget(self.descripcion_normal)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.boton_an_normal = QtWidgets.QPushButton(self.tab_escaneo)
        self.boton_an_normal.setObjectName("boton_an_normal")
        self.boton_an_normal.clicked.connect(self.inicia_escaneo_normal)
        self.horizontalLayout_13.addWidget(self.boton_an_normal)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.descripcion_profundo = QtWidgets.QLabel(self.tab_escaneo)
        self.descripcion_profundo.setObjectName("descripcion_profundo")
        self.verticalLayout_9.addWidget(self.descripcion_profundo)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.boton_an_profundo = QtWidgets.QPushButton(self.tab_escaneo)
        self.boton_an_profundo.setObjectName("boton_an_profundo")
        self.boton_an_profundo.clicked.connect(self.inicia_escaneo_profundo)
        self.horizontalLayout_12.addWidget(self.boton_an_profundo)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.horizontalLayout_17.addLayout(self.verticalLayout_12)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_ips_disponibles = QtWidgets.QLabel(self.tab_escaneo)
        self.label_ips_disponibles.setObjectName("label_ips_disponibles")
        self.verticalLayout_13.addWidget(self.label_ips_disponibles)
        self.panel_lista_ip = QtWidgets.QListWidget(self.tab_escaneo)
        self.panel_lista_ip.setObjectName("panel_lista_ip")
        self.verticalLayout_13.addWidget(self.panel_lista_ip)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.boton_seleccionar_ip = QtWidgets.QPushButton(self.tab_escaneo)
        self.boton_seleccionar_ip.setObjectName("boton_seleccionar_ip")
        self.boton_seleccionar_ip.setEnabled(False)
        self.horizontalLayout_11.addWidget(self.boton_seleccionar_ip)
        self.boton_cambiar_ip = QtWidgets.QPushButton(self.tab_escaneo)
        self.boton_cambiar_ip.setObjectName("boton_cambiar_ip")
        self.boton_cambiar_ip.setEnabled(False)
        self.horizontalLayout_11.addWidget(self.boton_cambiar_ip)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_17.addLayout(self.verticalLayout_14)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.ip_de_trabajo = QtWidgets.QLabel(self.tab_escaneo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ip_de_trabajo.setFont(font)
        self.ip_de_trabajo.setObjectName("ip_de_trabajo")
        self.verticalLayout_18.addWidget(self.ip_de_trabajo)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_info_red = QtWidgets.QLabel(self.tab_escaneo)
        self.label_info_red.setObjectName("label_info_red")
        self.verticalLayout_16.addWidget(self.label_info_red)
        self.panel_info_red = QtWidgets.QPlainTextEdit(self.tab_escaneo)
        self.panel_info_red.setObjectName("panel_info_red")
        self.verticalLayout_16.addWidget(self.panel_info_red)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_puertos = QtWidgets.QLabel(self.tab_escaneo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_puertos.setFont(font)
        self.label_puertos.setObjectName("label_puertos")
        self.verticalLayout_15.addWidget(self.label_puertos)
        self.descripcion_puertos = QtWidgets.QLabel(self.tab_escaneo)
        self.descripcion_puertos.setWordWrap(True)
        self.descripcion_puertos.setObjectName("descripcion_puertos")
        self.verticalLayout_15.addWidget(self.descripcion_puertos)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.boton_esc_puertos = QtWidgets.QPushButton(self.tab_escaneo)
        self.boton_esc_puertos.setObjectName("boton_esc_puertos")
        self.boton_esc_puertos.setEnabled(False)
        self.horizontalLayout_16.addWidget(self.boton_esc_puertos)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.horizontalLayout_17.addLayout(self.verticalLayout_18)
        self.verticalLayout_19.addLayout(self.horizontalLayout_17)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.tabWidget.addTab(self.tab_escaneo, "")
        self.tab_servicios = QtWidgets.QWidget()
        self.tab_servicios.setObjectName("tab_servicios")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab_servicios)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_servicios = QtWidgets.QLabel(self.tab_servicios)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_servicios.setFont(font)
        self.label_servicios.setObjectName("label_servicios")
        self.horizontalLayout_8.addWidget(self.label_servicios)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_http = QtWidgets.QLabel(self.tab_servicios)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_http.sizePolicy().hasHeightForWidth())
        self.label_http.setSizePolicy(sizePolicy)
        self.label_http.setMinimumSize(QtCore.QSize(20, 0))
        self.label_http.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_http.setObjectName("label_http")
        self.horizontalLayout_3.addWidget(self.label_http)
        self.boton_in_http = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_in_http.setObjectName("boton_in_http")
        self.boton_in_http.clicked.connect(self.inicia_http)
        self.horizontalLayout_3.addWidget(self.boton_in_http)
        self.boton_of_http = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_of_http.setObjectName("boton_of_http")
        self.boton_of_http.clicked.connect(self.apaga_servicio_http)
        self.boton_of_http.setVisible(False)
        self.horizontalLayout_3.addWidget(self.boton_of_http)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_ftp = QtWidgets.QLabel(self.tab_servicios)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ftp.sizePolicy().hasHeightForWidth())
        self.label_ftp.setSizePolicy(sizePolicy)
        self.label_ftp.setMinimumSize(QtCore.QSize(20, 0))
        self.label_ftp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_ftp.setObjectName("label_ftp")
        self.horizontalLayout_4.addWidget(self.label_ftp)
        self.boton_in_ftp = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_in_ftp.setObjectName("boton_in_ftp")
        self.boton_in_ftp.clicked.connect(self.inicia_ftp)
        self.horizontalLayout_4.addWidget(self.boton_in_ftp)
        self.boton_of_ftp = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_of_ftp.setObjectName("boton_of_ftp")
        self.boton_of_ftp.clicked.connect(self.apaga_servicio_ftp)
        self.boton_of_ftp.setVisible(False)
        self.horizontalLayout_4.addWidget(self.boton_of_ftp)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_telnet = QtWidgets.QLabel(self.tab_servicios)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_telnet.sizePolicy().hasHeightForWidth())
        self.label_telnet.setSizePolicy(sizePolicy)
        self.label_telnet.setMinimumSize(QtCore.QSize(20, 0))
        self.label_telnet.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_telnet.setObjectName("label_telnet")
        self.horizontalLayout_5.addWidget(self.label_telnet)
        self.boton_in_telnet = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_in_telnet.setObjectName("boton_in_telnet")
        self.boton_in_telnet.clicked.connect(self.inicia_telnet)
        self.horizontalLayout_5.addWidget(self.boton_in_telnet)
        self.boton_of_telnet = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_of_telnet.setObjectName("boton_of_telnet")
        self.boton_of_telnet.clicked.connect(self.apaga_servicio_telnet)
        self.boton_of_telnet.setVisible(False)
        self.horizontalLayout_5.addWidget(self.boton_of_telnet)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_estado = QtWidgets.QLabel(self.tab_servicios)
        self.label_estado.setObjectName("label_estado")
        self.verticalLayout_6.addWidget(self.label_estado)
        self.estado_http = QtWidgets.QLabel(self.tab_servicios)
        self.estado_http.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.estado_http.setObjectName("estado_http")
        self.verticalLayout_6.addWidget(self.estado_http)
        self.estado_ftp = QtWidgets.QLabel(self.tab_servicios)
        self.estado_ftp.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.estado_ftp.setObjectName("estado_ftp")
        self.verticalLayout_6.addWidget(self.estado_ftp)
        self.estado_telnet = QtWidgets.QLabel(self.tab_servicios)
        self.estado_telnet.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.estado_telnet.setObjectName("estado_telnet")
        self.verticalLayout_6.addWidget(self.estado_telnet)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_detalles_servicios = QtWidgets.QLabel(self.tab_servicios)
        self.label_detalles_servicios.setObjectName("label_detalles_servicios")
        self.verticalLayout_7.addWidget(self.label_detalles_servicios)
        self.panel_detalles_serv = QtWidgets.QPlainTextEdit(self.tab_servicios)
        self.panel_detalles_serv.setObjectName("panel_detalles_serv")
        self.verticalLayout_7.addWidget(self.panel_detalles_serv)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab_servicios, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ejecucion = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ejecucion.sizePolicy().hasHeightForWidth())
        self.label_ejecucion.setSizePolicy(sizePolicy)
        self.label_ejecucion.setObjectName("label_ejecucion")
        self.verticalLayout_2.addWidget(self.label_ejecucion)
        self.panel_ejecucion = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel_ejecucion.sizePolicy().hasHeightForWidth())
        self.panel_ejecucion.setSizePolicy(sizePolicy)
        self.panel_ejecucion.setMaximumSize(QtCore.QSize(16777215, 135))
        self.panel_ejecucion.setObjectName("panel_ejecucion")
        self.verticalLayout_2.addWidget(self.panel_ejecucion)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_resultados = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resultados.sizePolicy().hasHeightForWidth())
        self.label_resultados.setSizePolicy(sizePolicy)
        self.label_resultados.setObjectName("label_resultados")
        self.verticalLayout.addWidget(self.label_resultados)
        self.panel_resultados = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel_resultados.sizePolicy().hasHeightForWidth())
        self.panel_resultados.setSizePolicy(sizePolicy)
        self.panel_resultados.setMaximumSize(QtCore.QSize(16777215, 135))
        self.panel_resultados.setObjectName("panel_resultados")
        self.verticalLayout.addWidget(self.panel_resultados)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_progreso = QtWidgets.QLabel(self.centralwidget)
        self.label_progreso.setObjectName("label_progreso")
        self.horizontalLayout.addWidget(self.label_progreso)
        self.barra_progreso = QtWidgets.QProgressBar(self.centralwidget)
        self.barra_progreso.setProperty("value", 0)
        self.barra_progreso.setObjectName("barra_progreso")
        self.horizontalLayout.addWidget(self.barra_progreso)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.barra_menu = QtWidgets.QMenuBar(MainWindow)
        self.barra_menu.setGeometry(QtCore.QRect(0, 0, 846, 21))
        self.barra_menu.setObjectName("barra_menu")
        self.menuArchivo = QtWidgets.QMenu(self.barra_menu)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuServicios = QtWidgets.QMenu(self.barra_menu)
        self.menuServicios.setObjectName("menuServicios")
        self.menuAcerca_de = QtWidgets.QMenu(self.barra_menu)
        self.menuAcerca_de.setObjectName("menuAcerca_de")
        self.menuConfiguraciones = QtWidgets.QMenu(self.barra_menu)
        self.menuConfiguraciones.setObjectName("menuConfiguraciones")
        MainWindow.setMenuBar(self.barra_menu)
        self.barra_estado = QtWidgets.QStatusBar(MainWindow)
        self.barra_estado.setObjectName("barra_estado")
        MainWindow.setStatusBar(self.barra_estado)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionDetener_todos = QtWidgets.QAction(MainWindow)
        self.actionDetener_todos.setObjectName("actionDetener_todos")
        self.actionIniciar = QtWidgets.QAction(MainWindow)
        self.actionIniciar.setObjectName("actionIniciar")
        self.actionIniciar_todos = QtWidgets.QAction(MainWindow)
        self.actionIniciar_todos.setObjectName("actionIniciar_todos")
        self.actionPreferencias_de_an_lisis = QtWidgets.QAction(MainWindow)
        self.actionPreferencias_de_an_lisis.setObjectName("actionPreferencias_de_an_lisis")
        self.menuArchivo.addAction(self.actionSalir)
        self.menuServicios.addAction(self.actionIniciar_todos)
        self.menuServicios.addAction(self.actionDetener_todos)
        self.menuConfiguraciones.addAction(self.actionPreferencias_de_an_lisis)
        self.barra_menu.addAction(self.menuArchivo.menuAction())
        self.barra_menu.addAction(self.menuServicios.menuAction())
        self.barra_menu.addAction(self.menuConfiguraciones.menuAction())
        self.barra_menu.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo.setText(_translate("MainWindow", "Herramienta de análisis y servicios en red"))
        self.label_escaneo_actual.setText(_translate("MainWindow", "Escaneo de la red actual"))
        self.label_tipo_analisis.setText(_translate("MainWindow", "Tipo de análisis:"))
        self.descripcion_rapido.setText(_translate("MainWindow", "No garantiza la detección de todos los dispositivos"))
        self.boton_an_rapido.setText(_translate("MainWindow", "Análisis rápido"))
        self.descripcion_normal.setText(_translate("MainWindow", "Detecta más dispositivos en la red"))
        self.boton_an_normal.setText(_translate("MainWindow", "Análisis normal"))
        self.descripcion_profundo.setText(_translate("MainWindow", "Obtiene la mayor cantidad de dispositivos conectados"))
        self.boton_an_profundo.setText(_translate("MainWindow", "Análisis profundo"))
        self.label_ips_disponibles.setText(_translate("MainWindow", "IP\'s disponibles en la red"))
        self.boton_seleccionar_ip.setText(_translate("MainWindow", "Seleccionar"))
        self.boton_cambiar_ip.setText(_translate("MainWindow", "Cambiar"))
        self.ip_de_trabajo.setText(_translate("MainWindow", "IP de trabajo:"))
        self.label_info_red.setText(_translate("MainWindow", "Información de la red"))
        self.label_puertos.setText(_translate("MainWindow", "Escaneo de puertos"))
        self.descripcion_puertos.setText(_translate("MainWindow", "Esto permite saber qué puertos tiene abiertos la IP seleccionada"))
        self.boton_esc_puertos.setText(_translate("MainWindow", "Iniciar escaneo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_escaneo), _translate("MainWindow", "Escaneo de red"))
        self.label_servicios.setText(_translate("MainWindow", "Servicios y Servidores"))
        self.label_http.setText(_translate("MainWindow", "Servidor HTTP"))
        self.boton_in_http.setText(_translate("MainWindow", "Iniciar"))
        self.boton_of_http.setText(_translate("MainWindow", "Apagar"))
        self.label_ftp.setText(_translate("MainWindow", "Servidor FTP"))
        self.boton_in_ftp.setText(_translate("MainWindow", "Iniciar"))
        self.boton_of_ftp.setText(_translate("MainWindow", "Apagar"))
        self.label_telnet.setText(_translate("MainWindow", "Servidor Telnet"))
        self.boton_in_telnet.setText(_translate("MainWindow", "Iniciar"))
        self.boton_of_telnet.setText(_translate("MainWindow", "Apagar"))
        self.label_estado.setText(_translate("MainWindow", "Estado"))
        self.estado_http.setText(_translate("MainWindow", "0/1"))
        self.estado_ftp.setText(_translate("MainWindow", "0/1"))
        self.estado_telnet.setText(_translate("MainWindow", "0/1"))
        self.label_detalles_servicios.setText(_translate("MainWindow", "Detalles de los servidores en funcionamiento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_servicios), _translate("MainWindow", "Inicio de servicios"))
        self.label_ejecucion.setText(_translate("MainWindow", "Ejecución"))
        self.label_resultados.setText(_translate("MainWindow", "Resultados"))
        self.label_progreso.setText(_translate("MainWindow", "Progreso del análisis"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuServicios.setTitle(_translate("MainWindow", "Servicios"))
        self.menuAcerca_de.setTitle(_translate("MainWindow", "Acerca de"))
        self.menuConfiguraciones.setTitle(_translate("MainWindow", "Configuraciones"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionDetener_todos.setText(_translate("MainWindow", "Detener todos"))
        self.actionIniciar.setText(_translate("MainWindow", "Iniciar"))
        self.actionIniciar_todos.setText(_translate("MainWindow", "Iniciar todos"))
        self.actionPreferencias_de_an_lisis.setText(_translate("MainWindow", "Preferencias de análisis"))

    def get_active_hosts(self,z, t):
        ip_net = IPScanner.get_ip_net()
        all_hosts = list(ip_net.hosts())
        actives = []
        n = 1
        #self.panel_ejecucion.setPlainText("He comenzado a escanear las redes")
        #self.panel_ejecucion.appendPlainText("")
        plus = 100/255
        temp = 0
        #print(plus)
        try:
            for i in range(len(all_hosts)):
                output = subprocess.Popen(['ping', '-n', z, '-w', t, str(all_hosts[i])], stdout=subprocess.PIPE,
                                          startupinfo=IPScanner.info, ).communicate()[0]
                IP = str(all_hosts[i])
                print("Escaneando actualmente a: ", IP)
                temp += plus
                self.barra_progreso.setValue(temp)
                if "Respuesta desde " in output.decode('ISO-8859-1') and "TTL=" in output.decode('ISO-8859-1'):

                    from subprocess import Popen, PIPE
                    pid = Popen(["arp", "-n", IP], stdout=PIPE)
                    s = pid.communicate()[0]
                    comando = "arp -a " + IP
                    resultado = subprocess.check_output(comando, shell=True)
                    MAC_addr = str(resultado).replace('-', ':')
                    p = re.compile(r'([0-9a-f]{2}(?::[0-9a-f]{2}){5})', re.IGNORECASE)
                    mac = re.findall(p, MAC_addr)
                    nombre = socket.getfqdn(IP)
                    n += 1
                    if nombre.startswith("192.") and not nombre.endswith(".1") and not nombre.endswith(".254"):
                        clasificaciones = "[Dispositivo móvil]"
                    elif nombre.endswith(".254") or nombre.endswith(".1"):
                        clasificaciones = "[Módem raiz]"
                    else:
                        clasificaciones = "[Laptop/Desktop]"
                    if len(mac) <= 0:
                        mac = MACScanner.get_MAC_addr()
                    current = IPScanner.Net(IP, mac, clasificaciones, nombre)
                    actives.append(current)
        except Exception as e:
            print(e)
        self.barra_progreso.setValue(100)
        return actives

    def inicia_escaneo_rapido(self):
        hilo_escaneo_rapido = threading.Thread(target=self.escaneo_rapido)
        hilo_escaneo_rapido.start()

    def inicia_escaneo_normal(self):
        hilo_escaneo_normal = threading.Thread(target=self.escaneo_normal)
        hilo_escaneo_normal.start()

    def inicia_escaneo_profundo(self):
        hilo_escaneo_profundo = threading.Thread(target=self.escaneo_profundo)
        hilo_escaneo_profundo.start()

    def bloquea_botones_an(self):
        self.boton_an_normal.setEnabled(False)
        self.boton_an_rapido.setEnabled(False)
        self.boton_an_profundo.setEnabled(False)

    def escaneo_rapido(self):
        self.bloquea_botones_an()
        actives = self.get_active_hosts('1', '50')
        active_net,print = IPScanner.__initial__(actives)
        print("IP a trabajar: ", active_net.ip)
        self.panel_resultados.setPlainText(print)
        self.escaneo(active_net,actives)

    def escaneo_normal(self):
        self.bloquea_botones_an()
        actives = self.get_active_hosts('2', '50')
        active_net,print = IPScanner.__initial__(actives)
        self.panel_resultados.setPlainText(print)
        self.escaneo(active_net,actives)

    def escaneo_profundo(self):
        self.bloquea_botones_an()
        actives = self.get_active_hosts('3', '200')
        active_net,print = IPScanner.__initial__(actives)
        self.panel_resultados.setPlainText(print)
        self.escaneo(active_net,actives)

    def escaneo(self,current,list):
        ip = current.ip
        print("Actual: ", ip)
        print("IP:  ", current.ip)
        print("MAC: ", current.mac)
        print("NOM: ", current.name)
        print("CLS: ", current.classification)
        PortScanner.scan_ports(ip, 0, 150)
        IPScanner.print_actives(list)
        #ip = IPScanner.get_ip(list)

    def inicia_http(self):
        server_thread_http = threading.Thread(target=self.inicia_servicio_http)
        server_thread_http.start()

    def inicia_ftp(self):
        server_thread_ftp = threading.Thread(target=self.inicia_servicio_ftp)
        server_thread_ftp.start()

    def inicia_telnet(self):
        server_thread_tel = threading.Thread(target=self.inicia_servicio_telnet)
        server_thread_tel.start()

    def inicia_servicio_http(self):
        self.boton_in_http.setVisible(False)
        self.boton_of_http.setVisible(True)
        HTTPServer.inicia_servidor(IPScanner.getMyIpAddress(), 80, False)

    def apaga_servicio_http(self):
        self.boton_in_http.setVisible(True)
        self.boton_of_http.setVisible(False)
        print("Server turned off")
        try:
            HTTPServer.apaga_servidor()
        except:
            pass

    def inicia_servicio_ftp(self):
        self.boton_in_ftp.setVisible(False)
        self.boton_of_ftp.setVisible(True)
        FTPServer.inicia_servidor(IPScanner.getMyIpAddress(), 20)

    def apaga_servicio_ftp(self):
        self.boton_in_ftp.setVisible(True)
        self.boton_of_ftp.setVisible(False)
        print("Server turned off")
        try:
            FTPServer.apaga_servidor()
        except:
            pass

    def inicia_servicio_telnet(self):
        self.boton_in_telnet.setVisible(False)
        self.boton_of_telnet.setVisible(True)
        TelnetServer.inicia_servidor(IPScanner.getMyIpAddress(), 23)

    def apaga_servicio_telnet(self):
        self.boton_in_telnet.setVisible(True)
        self.boton_of_telnet.setVisible(False)
        print("Server turned off")
        try:
            TelnetServer.apaga_servidor()
        except:
            pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.aboutToQuit.connect(MainWindow.closeEvent)
    sys.exit(app.exec_())

