# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NetworkScanner.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_principal(object):
    def setupUi(self, principal):
        principal.setObjectName("principal")
        principal.resize(751, 416)
        self.centralwidget = QtWidgets.QWidget(principal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.tab_escaneo = QtWidgets.QWidget()
        self.tab_escaneo.setObjectName("tab_escaneo")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_escaneo)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.titulo_escaneo = QtWidgets.QLabel(self.tab_escaneo)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.titulo_escaneo.setFont(font)
        self.titulo_escaneo.setObjectName("titulo_escaneo")
        self.verticalLayout_13.addWidget(self.titulo_escaneo)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_tipo_an = QtWidgets.QLabel(self.tab_escaneo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_tipo_an.setFont(font)
        self.label_tipo_an.setObjectName("label_tipo_an")
        self.horizontalLayout_12.addWidget(self.label_tipo_an)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.boton_an_rapido = QtWidgets.QPushButton(self.tab_escaneo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_an_rapido.sizePolicy().hasHeightForWidth())
        self.boton_an_rapido.setSizePolicy(sizePolicy)
        self.boton_an_rapido.setMinimumSize(QtCore.QSize(100, 0))
        self.boton_an_rapido.setObjectName("boton_an_rapido")
        self.horizontalLayout_8.addWidget(self.boton_an_rapido)
        self.descr_an_rapido = QtWidgets.QLabel(self.tab_escaneo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descr_an_rapido.sizePolicy().hasHeightForWidth())
        self.descr_an_rapido.setSizePolicy(sizePolicy)
        self.descr_an_rapido.setMaximumSize(QtCore.QSize(150, 16777215))
        self.descr_an_rapido.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.descr_an_rapido.setWordWrap(True)
        self.descr_an_rapido.setObjectName("descr_an_rapido")
        self.horizontalLayout_8.addWidget(self.descr_an_rapido)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.boton_an_normal = QtWidgets.QPushButton(self.tab_escaneo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_an_normal.sizePolicy().hasHeightForWidth())
        self.boton_an_normal.setSizePolicy(sizePolicy)
        self.boton_an_normal.setMinimumSize(QtCore.QSize(100, 0))
        self.boton_an_normal.setObjectName("boton_an_normal")
        self.horizontalLayout_9.addWidget(self.boton_an_normal)
        self.desc_an_normal = QtWidgets.QLabel(self.tab_escaneo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc_an_normal.sizePolicy().hasHeightForWidth())
        self.desc_an_normal.setSizePolicy(sizePolicy)
        self.desc_an_normal.setMaximumSize(QtCore.QSize(150, 16777215))
        self.desc_an_normal.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.desc_an_normal.setWordWrap(True)
        self.desc_an_normal.setObjectName("desc_an_normal")
        self.horizontalLayout_9.addWidget(self.desc_an_normal)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.boton_an_profundo = QtWidgets.QPushButton(self.tab_escaneo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_an_profundo.sizePolicy().hasHeightForWidth())
        self.boton_an_profundo.setSizePolicy(sizePolicy)
        self.boton_an_profundo.setMinimumSize(QtCore.QSize(100, 0))
        self.boton_an_profundo.setObjectName("boton_an_profundo")
        self.horizontalLayout_10.addWidget(self.boton_an_profundo)
        self.desc_an_profundo = QtWidgets.QLabel(self.tab_escaneo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc_an_profundo.sizePolicy().hasHeightForWidth())
        self.desc_an_profundo.setSizePolicy(sizePolicy)
        self.desc_an_profundo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.desc_an_profundo.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.desc_an_profundo.setWordWrap(True)
        self.desc_an_profundo.setObjectName("desc_an_profundo")
        self.horizontalLayout_10.addWidget(self.desc_an_profundo)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_14.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_ip_disponibles = QtWidgets.QLabel(self.tab_escaneo)
        self.label_ip_disponibles.setObjectName("label_ip_disponibles")
        self.verticalLayout_7.addWidget(self.label_ip_disponibles)
        self.lista_ips = QtWidgets.QListWidget(self.tab_escaneo)
        self.lista_ips.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lista_ips.setObjectName("lista_ips")
        self.verticalLayout_7.addWidget(self.lista_ips)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.boton_seleccionar = QtWidgets.QPushButton(self.tab_escaneo)
        self.boton_seleccionar.setObjectName("boton_seleccionar")
        self.horizontalLayout_11.addWidget(self.boton_seleccionar)
        self.boton_cambiar = QtWidgets.QPushButton(self.tab_escaneo)
        self.boton_cambiar.setObjectName("boton_cambiar")
        self.horizontalLayout_11.addWidget(self.boton_cambiar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_ip_trabajo = QtWidgets.QLabel(self.tab_escaneo)
        self.label_ip_trabajo.setObjectName("label_ip_trabajo")
        self.verticalLayout_10.addWidget(self.label_ip_trabajo)
        self.panel_info_ip = QtWidgets.QTextEdit(self.tab_escaneo)
        self.panel_info_ip.setObjectName("panel_info_ip")
        self.verticalLayout_10.addWidget(self.panel_info_ip)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_puertos = QtWidgets.QLabel(self.tab_escaneo)
        self.label_puertos.setObjectName("label_puertos")
        self.horizontalLayout_13.addWidget(self.label_puertos)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.tab_escaneo)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.spinner_inferior = QtWidgets.QSpinBox(self.tab_escaneo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinner_inferior.sizePolicy().hasHeightForWidth())
        self.spinner_inferior.setSizePolicy(sizePolicy)
        self.spinner_inferior.setMinimumSize(QtCore.QSize(50, 0))
        self.spinner_inferior.setObjectName("spinner_inferior")
        self.horizontalLayout_6.addWidget(self.spinner_inferior)
        self.label = QtWidgets.QLabel(self.tab_escaneo)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.spinner_superior = QtWidgets.QSpinBox(self.tab_escaneo)
        self.spinner_superior.setMinimumSize(QtCore.QSize(50, 0))
        self.spinner_superior.setObjectName("spinner_superior")
        self.horizontalLayout_6.addWidget(self.spinner_superior)
        self.boton_puertos = QtWidgets.QPushButton(self.tab_escaneo)
        self.boton_puertos.setObjectName("boton_puertos")
        self.horizontalLayout_6.addWidget(self.boton_puertos)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_puertos_abiertos = QtWidgets.QLabel(self.tab_escaneo)
        self.label_puertos_abiertos.setObjectName("label_puertos_abiertos")
        self.verticalLayout_9.addWidget(self.label_puertos_abiertos)
        self.panel_puertos = QtWidgets.QTextEdit(self.tab_escaneo)
        self.panel_puertos.setObjectName("panel_puertos")
        self.verticalLayout_9.addWidget(self.panel_puertos)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.horizontalLayout_14.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_progreso = QtWidgets.QLabel(self.tab_escaneo)
        self.label_progreso.setObjectName("label_progreso")
        self.horizontalLayout_7.addWidget(self.label_progreso)
        self.barra_progreso = QtWidgets.QProgressBar(self.tab_escaneo)
        self.barra_progreso.setProperty("value", 24)
        self.barra_progreso.setObjectName("barra_progreso")
        self.horizontalLayout_7.addWidget(self.barra_progreso)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayout_15.addLayout(self.verticalLayout_13)
        self.tabs.addTab(self.tab_escaneo, "")
        self.tab_servicios = QtWidgets.QWidget()
        self.tab_servicios.setObjectName("tab_servicios")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_servicios)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.titulo_servicios = QtWidgets.QLabel(self.tab_servicios)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.titulo_servicios.setFont(font)
        self.titulo_servicios.setObjectName("titulo_servicios")
        self.verticalLayout_4.addWidget(self.titulo_servicios)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.desc_servicios = QtWidgets.QLabel(self.tab_servicios)
        self.desc_servicios.setObjectName("desc_servicios")
        self.verticalLayout_4.addWidget(self.desc_servicios)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_http = QtWidgets.QLabel(self.tab_servicios)
        self.label_http.setObjectName("label_http")
        self.horizontalLayout_2.addWidget(self.label_http)
        self.boton_in_http = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_in_http.setObjectName("boton_in_http")
        self.horizontalLayout_2.addWidget(self.boton_in_http)
        self.boton_off_http = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_off_http.setObjectName("boton_off_http")
        self.horizontalLayout_2.addWidget(self.boton_off_http)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_ftp = QtWidgets.QLabel(self.tab_servicios)
        self.label_ftp.setObjectName("label_ftp")
        self.horizontalLayout_3.addWidget(self.label_ftp)
        self.boton_in_ftp = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_in_ftp.setObjectName("boton_in_ftp")
        self.horizontalLayout_3.addWidget(self.boton_in_ftp)
        self.boton_off_ftp = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_off_ftp.setObjectName("boton_off_ftp")
        self.horizontalLayout_3.addWidget(self.boton_off_ftp)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_telnet = QtWidgets.QLabel(self.tab_servicios)
        self.label_telnet.setObjectName("label_telnet")
        self.horizontalLayout_4.addWidget(self.label_telnet)
        self.boton_in_telnet = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_in_telnet.setObjectName("boton_in_telnet")
        self.horizontalLayout_4.addWidget(self.boton_in_telnet)
        self.boton_off_telnet = QtWidgets.QPushButton(self.tab_servicios)
        self.boton_off_telnet.setObjectName("boton_off_telnet")
        self.horizontalLayout_4.addWidget(self.boton_off_telnet)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_estado = QtWidgets.QLabel(self.tab_servicios)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_estado.sizePolicy().hasHeightForWidth())
        self.label_estado.setSizePolicy(sizePolicy)
        self.label_estado.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_estado.setFont(font)
        self.label_estado.setAlignment(QtCore.Qt.AlignCenter)
        self.label_estado.setObjectName("label_estado")
        self.verticalLayout.addWidget(self.label_estado)
        self.estado_http = QtWidgets.QLabel(self.tab_servicios)
        self.estado_http.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.estado_http.setObjectName("estado_http")
        self.verticalLayout.addWidget(self.estado_http)
        self.estado_ftp = QtWidgets.QLabel(self.tab_servicios)
        self.estado_ftp.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.estado_ftp.setObjectName("estado_ftp")
        self.verticalLayout.addWidget(self.estado_ftp)
        self.estado_telnet = QtWidgets.QLabel(self.tab_servicios)
        self.estado_telnet.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.estado_telnet.setObjectName("estado_telnet")
        self.verticalLayout.addWidget(self.estado_telnet)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_detalles_serv = QtWidgets.QLabel(self.tab_servicios)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_detalles_serv.setFont(font)
        self.label_detalles_serv.setObjectName("label_detalles_serv")
        self.verticalLayout_2.addWidget(self.label_detalles_serv)
        self.panel_servicios = QtWidgets.QTextEdit(self.tab_servicios)
        self.panel_servicios.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel_servicios.sizePolicy().hasHeightForWidth())
        self.panel_servicios.setSizePolicy(sizePolicy)
        self.panel_servicios.setMinimumSize(QtCore.QSize(400, 0))
        self.panel_servicios.setObjectName("panel_servicios")
        self.verticalLayout_2.addWidget(self.panel_servicios)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.tabs.addTab(self.tab_servicios, "")
        self.verticalLayout_6.addWidget(self.tabs)
        principal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAcerca_de = QtWidgets.QMenu(self.menubar)
        self.menuAcerca_de.setObjectName("menuAcerca_de")
        principal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(principal)
        self.statusbar.setObjectName("statusbar")
        principal.setStatusBar(self.statusbar)
        self.actionEncender_todos_los_servidores = QtWidgets.QAction(principal)
        self.actionEncender_todos_los_servidores.setObjectName("actionEncender_todos_los_servidores")
        self.actionApagar_todos_los_servidores = QtWidgets.QAction(principal)
        self.actionApagar_todos_los_servidores.setObjectName("actionApagar_todos_los_servidores")
        self.actionSalir = QtWidgets.QAction(principal)
        self.actionSalir.setObjectName("actionSalir")
        self.actionSalir_2 = QtWidgets.QAction(principal)
        self.actionSalir_2.setObjectName("actionSalir_2")
        self.menuArchivo.addAction(self.actionEncender_todos_los_servidores)
        self.menuArchivo.addAction(self.actionApagar_todos_los_servidores)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir_2)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(principal)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(principal)

    def retranslateUi(self, principal):
        _translate = QtCore.QCoreApplication.translate
        principal.setWindowTitle(_translate("principal", "Herramienta de análisis y servicios en red"))
        self.titulo_escaneo.setText(_translate("principal", "Escaneo de la red actual"))
        self.label_tipo_an.setText(_translate("principal", "Tipo de análisis"))
        self.boton_an_rapido.setText(_translate("principal", "Análisis rápido"))
        self.descr_an_rapido.setText(_translate("principal", "No garantiza la detección de todos los dispositivos."))
        self.boton_an_normal.setText(_translate("principal", "Análisis normal"))
        self.desc_an_normal.setText(_translate("principal", "Detecta más dispositivos en la red que el rápido."))
        self.boton_an_profundo.setText(_translate("principal", "Análisis profundo"))
        self.desc_an_profundo.setText(_translate("principal", "Obtiene la mayor cantidad de dispositivos conectados"))
        self.label_ip_disponibles.setText(_translate("principal", "IP\'s disponibles en la red"))
        self.boton_seleccionar.setText(_translate("principal", "Seleccionar"))
        self.boton_cambiar.setText(_translate("principal", "Cambiar"))
        self.label_ip_trabajo.setText(_translate("principal", "IP de trabajo:"))
        self.label_puertos.setText(_translate("principal", "Escaneo de puertos"))
        self.label_2.setText(_translate("principal", "De"))
        self.label.setText(_translate("principal", "a"))
        self.boton_puertos.setText(_translate("principal", "Iniciar escaneo"))
        self.label_puertos_abiertos.setText(_translate("principal", "Puertos abiertos"))
        self.label_progreso.setText(_translate("principal", "Progreso del análisis"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_escaneo), _translate("principal", "Escaneo de red"))
        self.titulo_servicios.setText(_translate("principal", "Servicios y Servidores"))
        self.desc_servicios.setText(_translate("principal", "Los servidores de los que disponemos "))
        self.label_http.setText(_translate("principal", "Servidor HTTP"))
        self.boton_in_http.setText(_translate("principal", "Iniciar"))
        self.boton_off_http.setText(_translate("principal", "Apagar"))
        self.label_ftp.setText(_translate("principal", "Servidor FTP"))
        self.boton_in_ftp.setText(_translate("principal", "Iniciar"))
        self.boton_off_ftp.setText(_translate("principal", "Apagar"))
        self.label_telnet.setText(_translate("principal", "Servidor Telnet"))
        self.boton_in_telnet.setText(_translate("principal", "Iniciar"))
        self.boton_off_telnet.setText(_translate("principal", "Apagar"))
        self.label_estado.setText(_translate("principal", "Estado"))
        self.estado_http.setText(_translate("principal", "O"))
        self.estado_ftp.setText(_translate("principal", "O"))
        self.estado_telnet.setText(_translate("principal", "O"))
        self.label_detalles_serv.setText(_translate("principal", "Detalles de los servidores"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_servicios), _translate("principal", "Inicio de servicios"))
        self.menuArchivo.setTitle(_translate("principal", "Sistema"))
        self.menuAcerca_de.setTitle(_translate("principal", "Acerca de"))
        self.actionEncender_todos_los_servidores.setText(_translate("principal", "Encender todos los servidores"))
        self.actionApagar_todos_los_servidores.setText(_translate("principal", "Apagar todos los servidores"))
        self.actionSalir.setText(_translate("principal", "Salir"))
        self.actionSalir_2.setText(_translate("principal", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    principal = QtWidgets.QMainWindow()
    ui = Ui_principal()
    ui.setupUi(principal)
    principal.show()
    sys.exit(app.exec_())

